# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('uid', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=8)),
                ('lon', models.DecimalField(decimal_places=6, max_digits=8)),
                ('last_communication', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('SS', 'Started the server'), ('IS', 'Initiated search'), ('POI', 'Found a point of interest'), ('CS', 'Completed search'), ('RP', 'Received a point of interest from another team')], max_length=3)),
                ('headline', models.CharField(max_length=25)),
                ('text', models.CharField(max_length=150)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_new', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=8)),
                ('lon', models.DecimalField(decimal_places=6, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Pinor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=8)),
                ('lon', models.DecimalField(decimal_places=6, max_digits=8)),
                ('timestamp', models.DateTimeField()),
                ('origin', models.CharField(choices=[('M', 'My Team'), ('O', 'Other Team')], default='M', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='SearchArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(db_index=True, decimal_places=6, max_digits=8)),
                ('lon', models.DecimalField(db_index=True, decimal_places=6, max_digits=8)),
                ('status', models.CharField(choices=[('RE', 'Rescue Needed'), ('NRE', 'No Rescues Needed'), ('DD', 'Drones Dispatched'), ('NE', 'Not Explored')], max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='pinor',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='c2gui.SearchArea'),
        ),
        migrations.AddField(
            model_name='image',
            name='pinor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='c2gui.Pinor'),
        ),
        migrations.AddField(
            model_name='event',
            name='pinor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='c2gui.Pinor'),
        ),
        migrations.AddField(
            model_name='event',
            name='regions',
            field=models.ManyToManyField(to='c2gui.SearchArea'),
        ),
        migrations.AlterUniqueTogether(
            name='pinor',
            unique_together=set([('lat', 'lon')]),
        ),
        migrations.AlterUniqueTogether(
            name='image',
            unique_together=set([('lat', 'lon')]),
        ),
    ]
