# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 15:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('c2gui', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinor',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='c2gui.SearchArea'),
        ),
    ]
